global.userexist = 'user not exist'
global.userregistred = 'user registred successfully..!'
global.somethingwent = 'something went wrong'
global.credentials = 'check details'
global.userlogged = 'user loggedin successfully'
global.usernot = 'check details'
global.card = 'card status'
global.notcard = 'not found card'
global.noToken ="Token Required"
global.unauthorized ="unauthorized user"